<a href="https://colab.research.google.com/github/rohitmatere63/first-repo/blob/main/Starbucks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import datetime
import math

In [5]:
# portfolio--->offer info
#transcript--> customer interactions with offers -->transcript
# profile--> customer profile
# =============================================================================
portfolio=pd.read_csv('portfolio.csv')
transcript=pd.read_csv('transcript.csv')
profile=pd.read_csv(('profile.csv'))

In [6]:


profile['became_member_on']=pd.to_datetime(profile['became_member_on'],format='%Y%m%d')

profile.duplicated('id').any()
profile.head()
profile.info()


profile['gender']=profile['gender'].fillna('NA')

profile['income_na']=profile['income'].isna().astype(int)

profile['income']=profile['income'].fillna(profile['income'].mean())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        17000 non-null  int64
 1   gender            14825 non-null  object
 2   age               17000 non-null  int64
 3   id                17000 non-null  object
 4   became_member_on  17000 non-null  datetime64[ns]
 5   income            14825 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(2), object(2)
memory usage: 797.0+ KB

In [7]:
profile['year_joined']=profile['became_member_on'].dt.year

In [8]:
df=profile.copy()

In [9]:
profile=pd.get_dummies(profile,columns=['gender','year_joined'],dtype=int)

In [10]:
profile.drop('Unnamed: 0',axis=1)

,age,id,became_member_on,income,income_na,gender_F,gender_M,gender_NA,gender_O,year_joined_2013,year_joined_2014,year_joined_2015,year_joined_2016,year_joined_2017,year_joined_2018
0,118,68be06ca386d4c31939f3a4f0e3dd783,2017-02-12,65404.991568,1,0,0,1,0,0,0,0,0,1,0
1,55,0610b486422d4921ae7d2bf64640c50b,2017-07-15,112000.000000,0,1,0,0,0,0,0,0,0,1,0
2,118,38fe809add3b4fcf9315a9694bb96ff5,2018-07-12,65404.991568,1,0,0,1,0,0,0,0,0,0,1
3,75,78afa995795e4d85b5d9ceeca43f5fef,2017-05-09,100000.000000,0,1,0,0,0,0,0,0,0,1,0
4,118,a03223e636434f42ac4c3df47e8bac43,2017-08-04,65404.991568,1,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16995,45,6d5f3a774f3d4714ab0c092238f3a1d7,2018-06-04,54000.000000,0,1,0,0,0,0,0,0,0,0,1
16996,61,2cb4f97358b841b9a9773a7aa05a9d77,2018-07-13,72000.000000,0,0,1,0,0,0,0,0,0,0,1
16997,49,01d26f638c274aa0b965d24cefe3183f,2017-01-26,73000.000000,0,0,1,0,0,0,0,0,0,1,0
16998,83,9dc1421481194dcd9400aec7c9ae6366,2016-03-07,50000.000000,0,1,0,0,0,0,0,0,1,0,0
16999,62,e4052622e5ba45a8b96b59aba68cf068,2017-07-22,82000.000000,0,1,0,0,0,0,0,0,0,1,0

In [11]:
profile.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        17000 non-null  int64
 1   age               17000 non-null  int64
 2   id                17000 non-null  object
 3   became_member_on  17000 non-null  datetime64[ns]
 4   income            17000 non-null  float64
 5   income_na         17000 non-null  int64
 6   gender_F          17000 non-null  int64
 7   gender_M          17000 non-null  int64
 8   gender_NA         17000 non-null  int64
 9   gender_O          17000 non-null  int64
 10  year_joined_2013  17000 non-null  int64
 11  year_joined_2014  17000 non-null  int64
 12  year_joined_2015  17000 non-null  int64
 13  year_joined_2016  17000 non-null  int64
 14  year_joined_2017  17000 non-null  int64
 15  year_joined_2018  17000 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(13), object(1)
memory usage: 2.1+ MB

In [12]:
profile['income']=profile['income'].astype(int)

In [13]:
profile=profile.drop('became_member_on',axis=1)

In [14]:
profile=profile.drop('Unnamed: 0',axis=1)

In [15]:
transcript.head()

,Unnamed: 0,person,event,value,time
0,0,78afa995795e4d85b5d9ceeca43f5fef,offer received,{'offer id': '9b98b8c7a33c4b65b9aebfe6a799e6d9'},0
1,1,a03223e636434f42ac4c3df47e8bac43,offer received,{'offer id': '0b1e1539f2cc45b7b9fa7c272da2e1d7'},0
2,2,e2127556f4f64592b11af22de27a7932,offer received,{'offer id': '2906b810c7d4411798c6938adc9daaa5'},0
3,3,8ec6ce2a7e7949b1bf142def7d0e0586,offer received,{'offer id': 'fafdcd668e3743c1bb461111dcafc2a4'},0
4,4,68617ca6246f4fbc85e91a2a49552598,offer received,{'offer id': '4d5c57ea9a6940dd891ad53e9dbe8da0'},0

In [16]:
transcript.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 306534 entries, 0 to 306533
Data columns (total 5 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Unnamed: 0  306534 non-null  int64
 1   person      306534 non-null  object
 2   event       306534 non-null  object
 3   value       306534 non-null  object
 4   time        306534 non-null  int64
dtypes: int64(2), object(3)
memory usage: 11.7+ MB

In [17]:
transcript=pd.get_dummies(transcript,columns=['event'],dtype=int)

In [18]:
transcript.drop('Unnamed: 0',axis=1,inplace=True)

In [19]:
transcript.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 306534 entries, 0 to 306533
Data columns (total 7 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   person                 306534 non-null  object
 1   value                  306534 non-null  object
 2   time                   306534 non-null  int64
 3   event_offer completed  306534 non-null  int64
 4   event_offer received   306534 non-null  int64
 5   event_offer viewed     306534 non-null  int64
 6   event_transaction      306534 non-null  int64
dtypes: int64(5), object(2)
memory usage: 16.4+ MB

In [20]:
transcript['days_passed']=transcript['time']/24

In [21]:
transcript

,person,value,time,event_offer completed,event_offer received,event_offer viewed,event_transaction,days_passed
0,78afa995795e4d85b5d9ceeca43f5fef,{'offer id': '9b98b8c7a33c4b65b9aebfe6a799e6d9'},0,0,1,0,0,0.00
1,a03223e636434f42ac4c3df47e8bac43,{'offer id': '0b1e1539f2cc45b7b9fa7c272da2e1d7'},0,0,1,0,0,0.00
2,e2127556f4f64592b11af22de27a7932,{'offer id': '2906b810c7d4411798c6938adc9daaa5'},0,0,1,0,0,0.00
3,8ec6ce2a7e7949b1bf142def7d0e0586,{'offer id': 'fafdcd668e3743c1bb461111dcafc2a4'},0,0,1,0,0,0.00
4,68617ca6246f4fbc85e91a2a49552598,{'offer id': '4d5c57ea9a6940dd891ad53e9dbe8da0'},0,0,1,0,0,0.00
...,...,...,...,...,...,...,...,...
306529,b3a1272bc9904337b331bf348c3e8c17,{'amount': 1.5899999999999999},714,0,0,0,1,29.75
306530,68213b08d99a4ae1b0dcb72aebd9aa35,{'amount': 9.53},714,0,0,0,1,29.75
306531,a00058cf10334a308c68e7631c529907,{'amount': 3.61},714,0,0,0,1,29.75
306532,76ddbd6576844afe811f1a3c0fbb5bec,{'amount': 3.5300000000000002},714,0,0,0,1,29.75
306533,c02b10e8752c4d8e9b73f918558531f7,{'amount': 4.05},714,0,0,0,1,29.75

In [22]:
transcript.sample(5)

,person,value,time,event_offer completed,event_offer received,event_offer viewed,event_transaction,days_passed
145938,3bee268f105f4c5397ff326fcee03f7f,{'offer id': '5a8bc65990b245e5a138643cd4eb9837'},390,0,0,1,0,16.25
11954,6697f1cd4a774a0c93a6bf43462343c4,{'offer id': '0b1e1539f2cc45b7b9fa7c272da2e1d7'},0,0,1,0,0,0.00
302923,ca265792e65949d79b2b0e91bdd31c57,{'amount': 1.28},696,0,0,0,1,29.00
141281,7e0d5afd8f7c44178185a363ae80801c,{'offer id': '4d5c57ea9a6940dd891ad53e9dbe8da0'},372,0,0,1,0,15.50
92405,afe96b883fa846e9a972b73f8de5812f,{'amount': 1.58},240,0,0,0,1,10.00

In [23]:
transcript

,person,value,time,event_offer completed,event_offer received,event_offer viewed,event_transaction,days_passed
0,78afa995795e4d85b5d9ceeca43f5fef,{'offer id': '9b98b8c7a33c4b65b9aebfe6a799e6d9'},0,0,1,0,0,0.00
1,a03223e636434f42ac4c3df47e8bac43,{'offer id': '0b1e1539f2cc45b7b9fa7c272da2e1d7'},0,0,1,0,0,0.00
2,e2127556f4f64592b11af22de27a7932,{'offer id': '2906b810c7d4411798c6938adc9daaa5'},0,0,1,0,0,0.00
3,8ec6ce2a7e7949b1bf142def7d0e0586,{'offer id': 'fafdcd668e3743c1bb461111dcafc2a4'},0,0,1,0,0,0.00
4,68617ca6246f4fbc85e91a2a49552598,{'offer id': '4d5c57ea9a6940dd891ad53e9dbe8da0'},0,0,1,0,0,0.00
...,...,...,...,...,...,...,...,...
306529,b3a1272bc9904337b331bf348c3e8c17,{'amount': 1.5899999999999999},714,0,0,0,1,29.75
306530,68213b08d99a4ae1b0dcb72aebd9aa35,{'amount': 9.53},714,0,0,0,1,29.75
306531,a00058cf10334a308c68e7631c529907,{'amount': 3.61},714,0,0,0,1,29.75
306532,76ddbd6576844afe811f1a3c0fbb5bec,{'amount': 3.5300000000000002},714,0,0,0,1,29.75
306533,c02b10e8752c4d8e9b73f918558531f7,{'amount': 4.05},714,0,0,0,1,29.75

In [24]:
transaction=transcript.query('event_transaction==1')

In [25]:
transaction

,person,value,time,event_offer completed,event_offer received,event_offer viewed,event_transaction,days_passed
12654,02c083884c7d45b39cc68e1314fec56c,{'amount': 0.8300000000000001},0,0,0,0,1,0.00
12657,9fa9ae8f57894cc9a3b8a9bbe0fc1b2f,{'amount': 34.56},0,0,0,0,1,0.00
12659,54890f68699049c2a04d415abc25e717,{'amount': 13.23},0,0,0,0,1,0.00
12670,b2f1cd155b864803ad8334cdf13c4bd2,{'amount': 19.51},0,0,0,0,1,0.00
12671,fe97aa22dd3e48c8b143116a8403dd52,{'amount': 18.97},0,0,0,0,1,0.00
...,...,...,...,...,...,...,...,...
306529,b3a1272bc9904337b331bf348c3e8c17,{'amount': 1.5899999999999999},714,0,0,0,1,29.75
306530,68213b08d99a4ae1b0dcb72aebd9aa35,{'amount': 9.53},714,0,0,0,1,29.75
306531,a00058cf10334a308c68e7631c529907,{'amount': 3.61},714,0,0,0,1,29.75
306532,76ddbd6576844afe811f1a3c0fbb5bec,{'amount': 3.5300000000000002},714,0,0,0,1,29.75
306533,c02b10e8752c4d8e9b73f918558531f7,{'amount': 4.05},714,0,0,0,1,29.75

In [26]:
import ast

transaction['amount'] = transaction['value'].apply(lambda x: ast.literal_eval(x)['amount'])

/tmp/ipython-input-26-2340189880.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transaction['amount'] = transaction['value'].apply(lambda x: ast.literal_eval(x)['amount'])

In [27]:
transaction.drop(['event_offer completed','event_offer viewed','event_offer received'],axis=1,inplace=True)

/tmp/ipython-input-27-2646611195.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transaction.drop(['event_offer completed','event_offer viewed','event_offer received'],axis=1,inplace=True)

In [28]:
transaction

,person,value,time,event_transaction,days_passed,amount
12654,02c083884c7d45b39cc68e1314fec56c,{'amount': 0.8300000000000001},0,1,0.00,0.83
12657,9fa9ae8f57894cc9a3b8a9bbe0fc1b2f,{'amount': 34.56},0,1,0.00,34.56
12659,54890f68699049c2a04d415abc25e717,{'amount': 13.23},0,1,0.00,13.23
12670,b2f1cd155b864803ad8334cdf13c4bd2,{'amount': 19.51},0,1,0.00,19.51
12671,fe97aa22dd3e48c8b143116a8403dd52,{'amount': 18.97},0,1,0.00,18.97
...,...,...,...,...,...,...
306529,b3a1272bc9904337b331bf348c3e8c17,{'amount': 1.5899999999999999},714,1,29.75,1.59
306530,68213b08d99a4ae1b0dcb72aebd9aa35,{'amount': 9.53},714,1,29.75,9.53
306531,a00058cf10334a308c68e7631c529907,{'amount': 3.61},714,1,29.75,3.61
306532,76ddbd6576844afe811f1a3c0fbb5bec,{'amount': 3.5300000000000002},714,1,29.75,3.53
306533,c02b10e8752c4d8e9b73f918558531f7,{'amount': 4.05},714,1,29.75,4.05

In [29]:
transaction.drop('value',axis=1,inplace=True)

/tmp/ipython-input-29-3053752141.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transaction.drop('value',axis=1,inplace=True)

In [30]:
transaction

,person,time,event_transaction,days_passed,amount
12654,02c083884c7d45b39cc68e1314fec56c,0,1,0.00,0.83
12657,9fa9ae8f57894cc9a3b8a9bbe0fc1b2f,0,1,0.00,34.56
12659,54890f68699049c2a04d415abc25e717,0,1,0.00,13.23
12670,b2f1cd155b864803ad8334cdf13c4bd2,0,1,0.00,19.51
12671,fe97aa22dd3e48c8b143116a8403dd52,0,1,0.00,18.97
...,...,...,...,...,...
306529,b3a1272bc9904337b331bf348c3e8c17,714,1,29.75,1.59
306530,68213b08d99a4ae1b0dcb72aebd9aa35,714,1,29.75,9.53
306531,a00058cf10334a308c68e7631c529907,714,1,29.75,3.61
306532,76ddbd6576844afe811f1a3c0fbb5bec,714,1,29.75,3.53
306533,c02b10e8752c4d8e9b73f918558531f7,714,1,29.75,4.05

In [31]:
transcript

,person,value,time,event_offer completed,event_offer received,event_offer viewed,event_transaction,days_passed
0,78afa995795e4d85b5d9ceeca43f5fef,{'offer id': '9b98b8c7a33c4b65b9aebfe6a799e6d9'},0,0,1,0,0,0.00
1,a03223e636434f42ac4c3df47e8bac43,{'offer id': '0b1e1539f2cc45b7b9fa7c272da2e1d7'},0,0,1,0,0,0.00
2,e2127556f4f64592b11af22de27a7932,{'offer id': '2906b810c7d4411798c6938adc9daaa5'},0,0,1,0,0,0.00
3,8ec6ce2a7e7949b1bf142def7d0e0586,{'offer id': 'fafdcd668e3743c1bb461111dcafc2a4'},0,0,1,0,0,0.00
4,68617ca6246f4fbc85e91a2a49552598,{'offer id': '4d5c57ea9a6940dd891ad53e9dbe8da0'},0,0,1,0,0,0.00
...,...,...,...,...,...,...,...,...
306529,b3a1272bc9904337b331bf348c3e8c17,{'amount': 1.5899999999999999},714,0,0,0,1,29.75
306530,68213b08d99a4ae1b0dcb72aebd9aa35,{'amount': 9.53},714,0,0,0,1,29.75
306531,a00058cf10334a308c68e7631c529907,{'amount': 3.61},714,0,0,0,1,29.75
306532,76ddbd6576844afe811f1a3c0fbb5bec,{'amount': 3.5300000000000002},714,0,0,0,1,29.75
306533,c02b10e8752c4d8e9b73f918558531f7,{'amount': 4.05},714,0,0,0,1,29.75

In [32]:
offers=transcript.query('event_transaction!=1')

In [33]:
offers.drop('event_transaction',axis=1,inplace=True)

/tmp/ipython-input-33-4273392200.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  offers.drop('event_transaction',axis=1,inplace=True)

In [34]:
offers

,person,value,time,event_offer completed,event_offer received,event_offer viewed,days_passed
0,78afa995795e4d85b5d9ceeca43f5fef,{'offer id': '9b98b8c7a33c4b65b9aebfe6a799e6d9'},0,0,1,0,0.00
1,a03223e636434f42ac4c3df47e8bac43,{'offer id': '0b1e1539f2cc45b7b9fa7c272da2e1d7'},0,0,1,0,0.00
2,e2127556f4f64592b11af22de27a7932,{'offer id': '2906b810c7d4411798c6938adc9daaa5'},0,0,1,0,0.00
3,8ec6ce2a7e7949b1bf142def7d0e0586,{'offer id': 'fafdcd668e3743c1bb461111dcafc2a4'},0,0,1,0,0.00
4,68617ca6246f4fbc85e91a2a49552598,{'offer id': '4d5c57ea9a6940dd891ad53e9dbe8da0'},0,0,1,0,0.00
...,...,...,...,...,...,...,...
306497,a6f84f4e976f44508c358cc9aba6d2b3,{'offer_id': '2298d6c36e964ae4a3e7e9706d1fb8c2...,714,1,0,0,29.75
306506,b895c57e8cd047a8872ce02aa54759d6,{'offer_id': 'fafdcd668e3743c1bb461111dcafc2a4...,714,1,0,0,29.75
306507,8dda575c2a1d44b9ac8e8b07b93d1f8e,{'offer id': '0b1e1539f2cc45b7b9fa7c272da2e1d7'},714,0,0,1,29.75
306509,8431c16f8e1d440880db371a68f82dd0,{'offer_id': 'fafdcd668e3743c1bb461111dcafc2a4...,714,1,0,0,29.75
306527,24f56b5e1849462093931b164eb803b5,{'offer_id': 'fafdcd668e3743c1bb461111dcafc2a4...,714,1,0,0,29.75

In [35]:
def get_offer_id(value_str):
    try:
        return ast.literal_eval(value_str).get('offer id') or ast.literal_eval(value_str).get('offer_id')
    except SyntaxError:
        return None

offers['offer_id'] = offers['value'].apply(get_offer_id)
offers.dropna(subset=['offer_id'], inplace=True)

/tmp/ipython-input-35-1606850805.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  offers['offer_id'] = offers['value'].apply(get_offer_id)
/tmp/ipython-input-35-1606850805.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  offers.dropna(subset=['offer_id'], inplace=True)

In [36]:
offers.drop('value',axis=1,inplace=True)

/tmp/ipython-input-36-1214956087.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  offers.drop('value',axis=1,inplace=True)

In [37]:
offers

,person,time,event_offer completed,event_offer received,event_offer viewed,days_passed,offer_id
0,78afa995795e4d85b5d9ceeca43f5fef,0,0,1,0,0.00,9b98b8c7a33c4b65b9aebfe6a799e6d9
1,a03223e636434f42ac4c3df47e8bac43,0,0,1,0,0.00,0b1e1539f2cc45b7b9fa7c272da2e1d7
2,e2127556f4f64592b11af22de27a7932,0,0,1,0,0.00,2906b810c7d4411798c6938adc9daaa5
3,8ec6ce2a7e7949b1bf142def7d0e0586,0,0,1,0,0.00,fafdcd668e3743c1bb461111dcafc2a4
4,68617ca6246f4fbc85e91a2a49552598,0,0,1,0,0.00,4d5c57ea9a6940dd891ad53e9dbe8da0
...,...,...,...,...,...,...,...
306497,a6f84f4e976f44508c358cc9aba6d2b3,714,1,0,0,29.75,2298d6c36e964ae4a3e7e9706d1fb8c2
306506,b895c57e8cd047a8872ce02aa54759d6,714,1,0,0,29.75,fafdcd668e3743c1bb461111dcafc2a4
306507,8dda575c2a1d44b9ac8e8b07b93d1f8e,714,0,0,1,29.75,0b1e1539f2cc45b7b9fa7c272da2e1d7
306509,8431c16f8e1d440880db371a68f82dd0,714,1,0,0,29.75,fafdcd668e3743c1bb461111dcafc2a4
306527,24f56b5e1849462093931b164eb803b5,714,1,0,0,29.75,fafdcd668e3743c1bb461111dcafc2a4

In [38]:
portfolio

,Unnamed: 0,reward,channels,difficulty,duration,offer_type,id
0,0,10,"['email', 'mobile', 'social']",10,7,bogo,ae264e3637204a6fb9bb56bc8210ddfd
1,1,10,"['web', 'email', 'mobile', 'social']",10,5,bogo,4d5c57ea9a6940dd891ad53e9dbe8da0
2,2,0,"['web', 'email', 'mobile']",0,4,informational,3f207df678b143eea3cee63160fa8bed
3,3,5,"['web', 'email', 'mobile']",5,7,bogo,9b98b8c7a33c4b65b9aebfe6a799e6d9
4,4,5,"['web', 'email']",20,10,discount,0b1e1539f2cc45b7b9fa7c272da2e1d7
5,5,3,"['web', 'email', 'mobile', 'social']",7,7,discount,2298d6c36e964ae4a3e7e9706d1fb8c2
6,6,2,"['web', 'email', 'mobile', 'social']",10,10,discount,fafdcd668e3743c1bb461111dcafc2a4
7,7,0,"['email', 'mobile', 'social']",0,3,informational,5a8bc65990b245e5a138643cd4eb9837
8,8,5,"['web', 'email', 'mobile', 'social']",5,5,bogo,f19421c1d4aa40978ebb69ca19b0e20d
9,9,2,"['web', 'email', 'mobile']",10,7,discount,2906b810c7d4411798c6938adc9daaa5

In [39]:
import pandas as pd
import ast
from sklearn.preprocessing import MultiLabelBinarizer

# Step 1: Convert 'channels' from string to list
portfolio['channels'] = portfolio['channels'].apply(ast.literal_eval)

# Step 2: Apply MultiLabelBinarizer
mlb = MultiLabelBinarizer()
channels_encoded = mlb.fit_transform(portfolio['channels'])

# Step 3: Create a new DataFrame with channel columns
channels_df = pd.DataFrame(channels_encoded, columns=mlb.classes_)

# Step 4: Concatenate back to original portfolio DataFrame
portfolio = pd.concat([portfolio, channels_df], axis=1)

In [40]:
portfolio.columns

Index(['Unnamed: 0', 'reward', 'channels', 'difficulty', 'duration',
       'offer_type', 'id', 'email', 'mobile', 'social', 'web'],
      dtype='object')

In [41]:
portfolio.drop('Unnamed: 0',axis=1,inplace=True)

In [42]:
portfolio.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   reward      10 non-null     int64
 1   channels    10 non-null     object
 2   difficulty  10 non-null     int64
 3   duration    10 non-null     int64
 4   offer_type  10 non-null     object
 5   id          10 non-null     object
 6   email       10 non-null     int64
 7   mobile      10 non-null     int64
 8   social      10 non-null     int64
 9   web         10 non-null     int64
dtypes: int64(7), object(3)
memory usage: 932.0+ bytes

In [44]:
transcript.head(3)

,person,value,time,event_offer completed,event_offer received,event_offer viewed,event_transaction,days_passed
0,78afa995795e4d85b5d9ceeca43f5fef,{'offer id': '9b98b8c7a33c4b65b9aebfe6a799e6d9'},0,0,1,0,0,0.0
1,a03223e636434f42ac4c3df47e8bac43,{'offer id': '0b1e1539f2cc45b7b9fa7c272da2e1d7'},0,0,1,0,0,0.0
2,e2127556f4f64592b11af22de27a7932,{'offer id': '2906b810c7d4411798c6938adc9daaa5'},0,0,1,0,0,0.0

In [47]:
offers.head(1)

,person,time,event_offer completed,event_offer received,event_offer viewed,days_passed,offer_id
0,78afa995795e4d85b5d9ceeca43f5fef,0,0,1,0,0.0,9b98b8c7a33c4b65b9aebfe6a799e6d9

In [48]:
profile.head(1)

,age,id,income,income_na,gender_F,gender_M,gender_NA,gender_O,year_joined_2013,year_joined_2014,year_joined_2015,year_joined_2016,year_joined_2017,year_joined_2018
0,118,68be06ca386d4c31939f3a4f0e3dd783,65404,1,0,0,1,0,0,0,0,0,1,0

In [49]:
merged_df = pd.merge(offers, profile, left_on='person', right_on='id', how='left')

In [50]:
offers.query('person=="78afa995795e4d85b5d9ceeca43f5fef"	')

,person,time,event_offer completed,event_offer received,event_offer viewed,days_passed,offer_id
0,78afa995795e4d85b5d9ceeca43f5fef,0,0,1,0,0.00,9b98b8c7a33c4b65b9aebfe6a799e6d9
15561,78afa995795e4d85b5d9ceeca43f5fef,6,0,0,1,0.25,9b98b8c7a33c4b65b9aebfe6a799e6d9
47583,78afa995795e4d85b5d9ceeca43f5fef,132,1,0,0,5.50,9b98b8c7a33c4b65b9aebfe6a799e6d9
53176,78afa995795e4d85b5d9ceeca43f5fef,168,0,1,0,7.00,5a8bc65990b245e5a138643cd4eb9837
85291,78afa995795e4d85b5d9ceeca43f5fef,216,0,0,1,9.00,5a8bc65990b245e5a138643cd4eb9837
150598,78afa995795e4d85b5d9ceeca43f5fef,408,0,1,0,17.00,ae264e3637204a6fb9bb56bc8210ddfd
163375,78afa995795e4d85b5d9ceeca43f5fef,408,0,0,1,17.00,ae264e3637204a6fb9bb56bc8210ddfd
201572,78afa995795e4d85b5d9ceeca43f5fef,504,0,1,0,21.00,f19421c1d4aa40978ebb69ca19b0e20d
218394,78afa995795e4d85b5d9ceeca43f5fef,510,1,0,0,21.25,ae264e3637204a6fb9bb56bc8210ddfd
218395,78afa995795e4d85b5d9ceeca43f5fef,510,1,0,0,21.25,f19421c1d4aa40978ebb69ca19b0e20d
262138,78afa995795e4d85b5d9ceeca43f5fef,582,0,0,1,24.25,f19421c1d4aa40978ebb69ca19b0e20d

In [51]:
merged_df.query('person=="78afa995795e4d85b5d9ceeca43f5fef"	')

,person,time,event_offer completed,event_offer received,event_offer viewed,days_passed,offer_id,age,id,income,...,gender_F,gender_M,gender_NA,gender_O,year_joined_2013,year_joined_2014,year_joined_2015,year_joined_2016,year_joined_2017,year_joined_2018
0,78afa995795e4d85b5d9ceeca43f5fef,0,0,1,0,0.00,9b98b8c7a33c4b65b9aebfe6a799e6d9,75,78afa995795e4d85b5d9ceeca43f5fef,100000,...,1,0,0,0,0,0,0,0,1,0
14928,78afa995795e4d85b5d9ceeca43f5fef,6,0,0,1,0.25,9b98b8c7a33c4b65b9aebfe6a799e6d9,75,78afa995795e4d85b5d9ceeca43f5fef,100000,...,1,0,0,0,0,0,0,0,1,0
26541,78afa995795e4d85b5d9ceeca43f5fef,132,1,0,0,5.50,9b98b8c7a33c4b65b9aebfe6a799e6d9,75,78afa995795e4d85b5d9ceeca43f5fef,100000,...,1,0,0,0,0,0,0,0,1,0
27253,78afa995795e4d85b5d9ceeca43f5fef,168,0,1,0,7.00,5a8bc65990b245e5a138643cd4eb9837,75,78afa995795e4d85b5d9ceeca43f5fef,100000,...,1,0,0,0,0,0,0,0,1,0
50486,78afa995795e4d85b5d9ceeca43f5fef,216,0,0,1,9.00,5a8bc65990b245e5a138643cd4eb9837,75,78afa995795e4d85b5d9ceeca43f5fef,100000,...,1,0,0,0,0,0,0,0,1,0
80822,78afa995795e4d85b5d9ceeca43f5fef,408,0,1,0,17.00,ae264e3637204a6fb9bb56bc8210ddfd,75,78afa995795e4d85b5d9ceeca43f5fef,100000,...,1,0,0,0,0,0,0,0,1,0
93599,78afa995795e4d85b5d9ceeca43f5fef,408,0,0,1,17.00,ae264e3637204a6fb9bb56bc8210ddfd,75,78afa995795e4d85b5d9ceeca43f5fef,100000,...,1,0,0,0,0,0,0,0,1,0
109739,78afa995795e4d85b5d9ceeca43f5fef,504,0,1,0,21.00,f19421c1d4aa40978ebb69ca19b0e20d,75,78afa995795e4d85b5d9ceeca43f5fef,100000,...,1,0,0,0,0,0,0,0,1,0
125208,78afa995795e4d85b5d9ceeca43f5fef,510,1,0,0,21.25,ae264e3637204a6fb9bb56bc8210ddfd,75,78afa995795e4d85b5d9ceeca43f5fef,100000,...,1,0,0,0,0,0,0,0,1,0
125209,78afa995795e4d85b5d9ceeca43f5fef,510,1,0,0,21.25,f19421c1d4aa40978ebb69ca19b0e20d,75,78afa995795e4d85b5d9ceeca43f5fef,100000,...,1,0,0,0,0,0,0,0,1,0
152309,78afa995795e4d85b5d9ceeca43f5fef,582,0,0,1,24.25,f19421c1d4aa40978ebb69ca19b0e20d,75,78afa995795e4d85b5d9ceeca43f5fef,100000,...,1,0,0,0,0,0,0,0,1,0

In [52]:
offers.shape

(167581, 7)

In [53]:
portfolio

,reward,channels,difficulty,duration,offer_type,id,email,mobile,social,web
0,10,"[email, mobile, social]",10,7,bogo,ae264e3637204a6fb9bb56bc8210ddfd,1,1,1,0
1,10,"[web, email, mobile, social]",10,5,bogo,4d5c57ea9a6940dd891ad53e9dbe8da0,1,1,1,1
2,0,"[web, email, mobile]",0,4,informational,3f207df678b143eea3cee63160fa8bed,1,1,0,1
3,5,"[web, email, mobile]",5,7,bogo,9b98b8c7a33c4b65b9aebfe6a799e6d9,1,1,0,1
4,5,"[web, email]",20,10,discount,0b1e1539f2cc45b7b9fa7c272da2e1d7,1,0,0,1
5,3,"[web, email, mobile, social]",7,7,discount,2298d6c36e964ae4a3e7e9706d1fb8c2,1,1,1,1
6,2,"[web, email, mobile, social]",10,10,discount,fafdcd668e3743c1bb461111dcafc2a4,1,1,1,1
7,0,"[email, mobile, social]",0,3,informational,5a8bc65990b245e5a138643cd4eb9837,1,1,1,0
8,5,"[web, email, mobile, social]",5,5,bogo,f19421c1d4aa40978ebb69ca19b0e20d,1,1,1,1
9,2,"[web, email, mobile]",10,7,discount,2906b810c7d4411798c6938adc9daaa5,1,1,0,1

In [54]:
o=merged_df.copy()

In [55]:
o=o.merge(portfolio,left_on='offer_id',right_on='id')

In [57]:
o.drop(['id_y','id_x'],axis=1,inplace=True)

In [58]:
o.columns

Index(['person', 'time', 'event_offer completed', 'event_offer received',
       'event_offer viewed', 'days_passed', 'offer_id', 'age', 'income',
       'income_na', 'gender_F', 'gender_M', 'gender_NA', 'gender_O',
       'year_joined_2013', 'year_joined_2014', 'year_joined_2015',
       'year_joined_2016', 'year_joined_2017', 'year_joined_2018', 'reward',
       'channels', 'difficulty', 'duration', 'offer_type', 'email', 'mobile',
       'social', 'web'],
      dtype='object')

In [59]:
o.drop('channels',axis=1,inplace=True)

In [60]:
o

,person,time,event_offer completed,event_offer received,event_offer viewed,days_passed,offer_id,age,income,income_na,...,year_joined_2017,year_joined_2018,reward,difficulty,duration,offer_type,email,mobile,social,web
0,78afa995795e4d85b5d9ceeca43f5fef,0,0,1,0,0.00,9b98b8c7a33c4b65b9aebfe6a799e6d9,75,100000,0,...,1,0,5,5,7,bogo,1,1,0,1
1,a03223e636434f42ac4c3df47e8bac43,0,0,1,0,0.00,0b1e1539f2cc45b7b9fa7c272da2e1d7,118,65404,1,...,1,0,5,20,10,discount,1,0,0,1
2,e2127556f4f64592b11af22de27a7932,0,0,1,0,0.00,2906b810c7d4411798c6938adc9daaa5,68,70000,0,...,0,1,2,10,7,discount,1,1,0,1
3,8ec6ce2a7e7949b1bf142def7d0e0586,0,0,1,0,0.00,fafdcd668e3743c1bb461111dcafc2a4,118,65404,1,...,1,0,2,10,10,discount,1,1,1,1
4,68617ca6246f4fbc85e91a2a49552598,0,0,1,0,0.00,4d5c57ea9a6940dd891ad53e9dbe8da0,118,65404,1,...,1,0,10,10,5,bogo,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167576,a6f84f4e976f44508c358cc9aba6d2b3,714,1,0,0,29.75,2298d6c36e964ae4a3e7e9706d1fb8c2,118,65404,1,...,1,0,3,7,7,discount,1,1,1,1
167577,b895c57e8cd047a8872ce02aa54759d6,714,1,0,0,29.75,fafdcd668e3743c1bb461111dcafc2a4,118,65404,1,...,1,0,2,10,10,discount,1,1,1,1
167578,8dda575c2a1d44b9ac8e8b07b93d1f8e,714,0,0,1,29.75,0b1e1539f2cc45b7b9fa7c272da2e1d7,60,64000,0,...,1,0,5,20,10,discount,1,0,0,1
167579,8431c16f8e1d440880db371a68f82dd0,714,1,0,0,29.75,fafdcd668e3743c1bb461111dcafc2a4,39,39000,0,...,0,1,2,10,10,discount,1,1,1,1
167580,24f56b5e1849462093931b164eb803b5,714,1,0,0,29.75,fafdcd668e3743c1bb461111dcafc2a4,48,80000,0,...,1,0,2,10,10,discount,1,1,1,1

In [74]:
offer_type_dummies = o['offer_type'].str.get_dummies()

In [75]:
o=pd.concat([o,offer_type_dummies],axis=1)

In [76]:
o

,person,time,event_offer completed,event_offer received,event_offer viewed,days_passed,offer_id,age,income,income_na,...,difficulty,duration,offer_type,email,mobile,social,web,bogo,discount,informational
0,78afa995795e4d85b5d9ceeca43f5fef,0,0,1,0,0.00,9b98b8c7a33c4b65b9aebfe6a799e6d9,75,100000,0,...,5,7,bogo,1,1,0,1,1,0,0
1,a03223e636434f42ac4c3df47e8bac43,0,0,1,0,0.00,0b1e1539f2cc45b7b9fa7c272da2e1d7,118,65404,1,...,20,10,discount,1,0,0,1,0,1,0
2,e2127556f4f64592b11af22de27a7932,0,0,1,0,0.00,2906b810c7d4411798c6938adc9daaa5,68,70000,0,...,10,7,discount,1,1,0,1,0,1,0
3,8ec6ce2a7e7949b1bf142def7d0e0586,0,0,1,0,0.00,fafdcd668e3743c1bb461111dcafc2a4,118,65404,1,...,10,10,discount,1,1,1,1,0,1,0
4,68617ca6246f4fbc85e91a2a49552598,0,0,1,0,0.00,4d5c57ea9a6940dd891ad53e9dbe8da0,118,65404,1,...,10,5,bogo,1,1,1,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167576,a6f84f4e976f44508c358cc9aba6d2b3,714,1,0,0,29.75,2298d6c36e964ae4a3e7e9706d1fb8c2,118,65404,1,...,7,7,discount,1,1,1,1,0,1,0
167577,b895c57e8cd047a8872ce02aa54759d6,714,1,0,0,29.75,fafdcd668e3743c1bb461111dcafc2a4,118,65404,1,...,10,10,discount,1,1,1,1,0,1,0
167578,8dda575c2a1d44b9ac8e8b07b93d1f8e,714,0,0,1,29.75,0b1e1539f2cc45b7b9fa7c272da2e1d7,60,64000,0,...,20,10,discount,1,0,0,1,0,1,0
167579,8431c16f8e1d440880db371a68f82dd0,714,1,0,0,29.75,fafdcd668e3743c1bb461111dcafc2a4,39,39000,0,...,10,10,discount,1,1,1,1,0,1,0
167580,24f56b5e1849462093931b164eb803b5,714,1,0,0,29.75,fafdcd668e3743c1bb461111dcafc2a4,48,80000,0,...,10,10,discount,1,1,1,1,0,1,0

In [77]:
transcript

,person,value,time,event_offer completed,event_offer received,event_offer viewed,event_transaction,days_passed
0,78afa995795e4d85b5d9ceeca43f5fef,{'offer id': '9b98b8c7a33c4b65b9aebfe6a799e6d9'},0,0,1,0,0,0.00
1,a03223e636434f42ac4c3df47e8bac43,{'offer id': '0b1e1539f2cc45b7b9fa7c272da2e1d7'},0,0,1,0,0,0.00
2,e2127556f4f64592b11af22de27a7932,{'offer id': '2906b810c7d4411798c6938adc9daaa5'},0,0,1,0,0,0.00
3,8ec6ce2a7e7949b1bf142def7d0e0586,{'offer id': 'fafdcd668e3743c1bb461111dcafc2a4'},0,0,1,0,0,0.00
4,68617ca6246f4fbc85e91a2a49552598,{'offer id': '4d5c57ea9a6940dd891ad53e9dbe8da0'},0,0,1,0,0,0.00
...,...,...,...,...,...,...,...,...
306529,b3a1272bc9904337b331bf348c3e8c17,{'amount': 1.5899999999999999},714,0,0,0,1,29.75
306530,68213b08d99a4ae1b0dcb72aebd9aa35,{'amount': 9.53},714,0,0,0,1,29.75
306531,a00058cf10334a308c68e7631c529907,{'amount': 3.61},714,0,0,0,1,29.75
306532,76ddbd6576844afe811f1a3c0fbb5bec,{'amount': 3.5300000000000002},714,0,0,0,1,29.75
306533,c02b10e8752c4d8e9b73f918558531f7,{'amount': 4.05},714,0,0,0,1,29.75

In [79]:
transaction=transaction.merge(profile,left_on='person',right_on='id')

In [80]:
transaction

,person,time,event_transaction,days_passed,amount,age,id,income,income_na,gender_F,gender_M,gender_NA,gender_O,year_joined_2013,year_joined_2014,year_joined_2015,year_joined_2016,year_joined_2017,year_joined_2018
0,02c083884c7d45b39cc68e1314fec56c,0,1,0.00,0.83,20,02c083884c7d45b39cc68e1314fec56c,30000,0,1,0,0,0,0,0,0,1,0,0
1,9fa9ae8f57894cc9a3b8a9bbe0fc1b2f,0,1,0.00,34.56,42,9fa9ae8f57894cc9a3b8a9bbe0fc1b2f,96000,0,0,1,0,0,0,0,0,1,0,0
2,54890f68699049c2a04d415abc25e717,0,1,0.00,13.23,36,54890f68699049c2a04d415abc25e717,56000,0,0,1,0,0,0,0,0,0,1,0
3,b2f1cd155b864803ad8334cdf13c4bd2,0,1,0.00,19.51,55,b2f1cd155b864803ad8334cdf13c4bd2,94000,0,1,0,0,0,0,0,0,0,1,0
4,fe97aa22dd3e48c8b143116a8403dd52,0,1,0.00,18.97,39,fe97aa22dd3e48c8b143116a8403dd52,67000,0,1,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138948,b3a1272bc9904337b331bf348c3e8c17,714,1,29.75,1.59,66,b3a1272bc9904337b331bf348c3e8c17,47000,0,0,1,0,0,0,0,0,0,0,1
138949,68213b08d99a4ae1b0dcb72aebd9aa35,714,1,29.75,9.53,52,68213b08d99a4ae1b0dcb72aebd9aa35,62000,0,0,1,0,0,0,0,0,0,0,1
138950,a00058cf10334a308c68e7631c529907,714,1,29.75,3.61,63,a00058cf10334a308c68e7631c529907,52000,0,1,0,0,0,1,0,0,0,0,0
138951,76ddbd6576844afe811f1a3c0fbb5bec,714,1,29.75,3.53,57,76ddbd6576844afe811f1a3c0fbb5bec,40000,0,0,1,0,0,0,0,0,1,0,0
138952,c02b10e8752c4d8e9b73f918558531f7,714,1,29.75,4.05,118,c02b10e8752c4d8e9b73f918558531f7,65404,1,0,0,1,0,0,0,1,0,0,0

In [81]:
transaction.drop(['id','event_transaction'],axis=1,inplace=True)

In [88]:
offers=o.copy()

In [92]:
profile = profile.query('age <= 99')
offers = offers.query('age <= 99')
transaction = transaction.query('age <= 99')

In [93]:
# the same offer can be received and viewed multiple times
offers[offers.duplicated(subset=['offer_id', 'person'], keep=False)].head()

,person,time,event_offer completed,event_offer received,event_offer viewed,days_passed,offer_id,age,income,income_na,...,difficulty,duration,offer_type,email,mobile,social,web,bogo,discount,informational
0,78afa995795e4d85b5d9ceeca43f5fef,0,0,1,0,0.0,9b98b8c7a33c4b65b9aebfe6a799e6d9,75,100000,0,...,5,7,bogo,1,1,0,1,1,0,0
2,e2127556f4f64592b11af22de27a7932,0,0,1,0,0.0,2906b810c7d4411798c6938adc9daaa5,68,70000,0,...,10,7,discount,1,1,0,1,0,1,0
5,389bc3fa690240e798340f5a15918d5c,0,0,1,0,0.0,f19421c1d4aa40978ebb69ca19b0e20d,65,53000,0,...,5,5,bogo,1,1,1,1,1,0,0
8,aa4862eba776480b8bb9c68455b8c2e1,0,0,1,0,0.0,0b1e1539f2cc45b7b9fa7c272da2e1d7,61,57000,0,...,20,10,discount,1,0,0,1,0,1,0
9,31dda685af34476cad5bc968bdb01c53,0,0,1,0,0.0,0b1e1539f2cc45b7b9fa7c272da2e1d7,62,71000,0,...,20,10,discount,1,0,0,1,0,1,0

In [94]:
offers.columns

Index(['person', 'time', 'event_offer completed', 'event_offer received',
       'event_offer viewed', 'days_passed', 'offer_id', 'age', 'income',
       'income_na', 'gender_F', 'gender_M', 'gender_NA', 'gender_O',
       'year_joined_2013', 'year_joined_2014', 'year_joined_2015',
       'year_joined_2016', 'year_joined_2017', 'year_joined_2018', 'reward',
       'difficulty', 'duration', 'offer_type', 'email', 'mobile', 'social',
       'web', 'bogo', 'discount', 'informational'],
      dtype='object')

In [95]:


# Assuming df is your DataFrame
def get_event(row):
    if row['event_offer completed'] == 1:
        return 'offer completed'
    elif row['event_offer viewed'] == 1:
        return 'offer viewed'
    elif row['event_offer received'] == 1:
        return 'offer received'
    else:
        return np.nan

offers['event'] = offers.apply(get_event, axis=1)

In [104]:
offers.query('person=="78afa995795e4d85b5d9ceeca43f5fef"	')

,person,time,event_offer completed,event_offer received,event_offer viewed,days_passed,offer_id,age,income,income_na,...,duration,offer_type,email,mobile,social,web,bogo,discount,informational,event
0,78afa995795e4d85b5d9ceeca43f5fef,0,0,1,0,0.00,9b98b8c7a33c4b65b9aebfe6a799e6d9,75,100000,0,...,7,bogo,1,1,0,1,1,0,0,offer received
14928,78afa995795e4d85b5d9ceeca43f5fef,6,0,0,1,0.25,9b98b8c7a33c4b65b9aebfe6a799e6d9,75,100000,0,...,7,bogo,1,1,0,1,1,0,0,offer viewed
26541,78afa995795e4d85b5d9ceeca43f5fef,132,1,0,0,5.50,9b98b8c7a33c4b65b9aebfe6a799e6d9,75,100000,0,...,7,bogo,1,1,0,1,1,0,0,offer completed
27253,78afa995795e4d85b5d9ceeca43f5fef,168,0,1,0,7.00,5a8bc65990b245e5a138643cd4eb9837,75,100000,0,...,3,informational,1,1,1,0,0,0,1,offer received
50486,78afa995795e4d85b5d9ceeca43f5fef,216,0,0,1,9.00,5a8bc65990b245e5a138643cd4eb9837,75,100000,0,...,3,informational,1,1,1,0,0,0,1,offer viewed
80822,78afa995795e4d85b5d9ceeca43f5fef,408,0,1,0,17.00,ae264e3637204a6fb9bb56bc8210ddfd,75,100000,0,...,7,bogo,1,1,1,0,1,0,0,offer received
93599,78afa995795e4d85b5d9ceeca43f5fef,408,0,0,1,17.00,ae264e3637204a6fb9bb56bc8210ddfd,75,100000,0,...,7,bogo,1,1,1,0,1,0,0,offer viewed
109739,78afa995795e4d85b5d9ceeca43f5fef,504,0,1,0,21.00,f19421c1d4aa40978ebb69ca19b0e20d,75,100000,0,...,5,bogo,1,1,1,1,1,0,0,offer received
125208,78afa995795e4d85b5d9ceeca43f5fef,510,1,0,0,21.25,ae264e3637204a6fb9bb56bc8210ddfd,75,100000,0,...,7,bogo,1,1,1,0,1,0,0,offer completed
125209,78afa995795e4d85b5d9ceeca43f5fef,510,1,0,0,21.25,f19421c1d4aa40978ebb69ca19b0e20d,75,100000,0,...,5,bogo,1,1,1,1,1,0,0,offer completed
152309,78afa995795e4d85b5d9ceeca43f5fef,582,0,0,1,24.25,f19421c1d4aa40978ebb69ca19b0e20d,75,100000,0,...,5,bogo,1,1,1,1,1,0,0,offer viewed

In [103]:
offers.info()

<class 'pandas.core.frame.DataFrame'>
Index: 148628 entries, 0 to 167580
Data columns (total 32 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   person                 148628 non-null  object
 1   time                   148628 non-null  int64
 2   event_offer completed  148628 non-null  int64
 3   event_offer received   148628 non-null  int64
 4   event_offer viewed     148628 non-null  int64
 5   days_passed            148628 non-null  float64
 6   offer_id               148628 non-null  object
 7   age                    148628 non-null  int64
 8   income                 148628 non-null  int64
 9   income_na              148628 non-null  int64
 10  gender_F               148628 non-null  int64
 11  gender_M               148628 non-null  int64
 12  gender_NA              148628 non-null  int64
 13  gender_O               148628 non-null  int64
 14  year_joined_2013       148628 non-null  int64
 15  year_joined_2014       148628 non-null  int64
 16  year_joined_2015       148628 non-null  int64
 17  year_joined_2016       148628 non-null  int64
 18  year_joined_2017       148628 non-null  int64
 19  year_joined_2018       148628 non-null  int64
 20  reward                 148628 non-null  int64
 21  difficulty             148628 non-null  int64
 22  duration               148628 non-null  int64
 23  offer_type             148628 non-null  object
 24  email                  148628 non-null  int64
 25  mobile                 148628 non-null  int64
 26  social                 148628 non-null  int64
 27  web                    148628 non-null  int64
 28  bogo                   148628 non-null  int64
 29  discount               148628 non-null  int64
 30  informational          148628 non-null  int64
 31  event                  148628 non-null  object
dtypes: float64(1), int64(27), object(4)
memory usage: 37.4+ MB

In [106]:
# add receipt, view and completion time columns
offers['time'] = offers['time'] + 0.5
offers['received_time'] = offers['event_offer received'] * offers['time']
offers['viewed_time'] = offers['event_offer viewed'] * offers['time']
offers['completed_time'] = offers['event_offer completed'] * offers['time']
offers.head()

,person,time,event_offer completed,event_offer received,event_offer viewed,days_passed,offer_id,age,income,income_na,...,mobile,social,web,bogo,discount,informational,event,received_time,viewed_time,completed_time
0,78afa995795e4d85b5d9ceeca43f5fef,0.5,0,1,0,0.0,9b98b8c7a33c4b65b9aebfe6a799e6d9,75,100000,0,...,1,0,1,1,0,0,offer received,0.5,0.0,0.0
2,e2127556f4f64592b11af22de27a7932,0.5,0,1,0,0.0,2906b810c7d4411798c6938adc9daaa5,68,70000,0,...,1,0,1,0,1,0,offer received,0.5,0.0,0.0
5,389bc3fa690240e798340f5a15918d5c,0.5,0,1,0,0.0,f19421c1d4aa40978ebb69ca19b0e20d,65,53000,0,...,1,1,1,1,0,0,offer received,0.5,0.0,0.0
7,2eeac8d8feae4a8cad5a6af0499a211d,0.5,0,1,0,0.0,3f207df678b143eea3cee63160fa8bed,58,51000,0,...,1,0,1,0,0,1,offer received,0.5,0.0,0.0
8,aa4862eba776480b8bb9c68455b8c2e1,0.5,0,1,0,0.0,0b1e1539f2cc45b7b9fa7c272da2e1d7,61,57000,0,...,0,0,1,0,1,0,offer received,0.5,0.0,0.0

In [107]:
# an offer can be received multiple times by the same person
# we'll use first exposure times, but keep track of the number of exposures

offers_mins = offers.groupby(['person', 'offer_id', 'event']).min()
offers_sums = offers.groupby(['person', 'offer_id', 'event'])[['event_offer received', 'event_offer viewed', 'event_offer completed']].sum()

offers_mins.update(offers_sums)

offers_grouped = offers_mins.groupby(['person', 'offer_id']).max().reset_index()

offers_grouped.fillna(0, inplace=True)

offers_grouped.head()

,person,offer_id,time,event_offer completed,event_offer received,event_offer viewed,days_passed,age,income,income_na,...,email,mobile,social,web,bogo,discount,informational,received_time,viewed_time,completed_time
0,0009655768c64bdeb2e877511632db8f,2906b810c7d4411798c6938adc9daaa5,576.5,1,1,0,24.0,33,72000,0,...,1,1,0,1,0,1,0,576.5,0.0,576.5
1,0009655768c64bdeb2e877511632db8f,3f207df678b143eea3cee63160fa8bed,372.5,0,1,1,15.5,33,72000,0,...,1,1,0,1,0,0,1,336.5,372.5,0.0
2,0009655768c64bdeb2e877511632db8f,5a8bc65990b245e5a138643cd4eb9837,192.5,0,1,1,8.0,33,72000,0,...,1,1,1,0,0,0,1,168.5,192.5,0.0
3,0009655768c64bdeb2e877511632db8f,f19421c1d4aa40978ebb69ca19b0e20d,456.5,1,1,1,19.0,33,72000,0,...,1,1,1,1,1,0,0,408.5,456.5,414.5
4,0009655768c64bdeb2e877511632db8f,fafdcd668e3743c1bb461111dcafc2a4,540.5,1,1,1,22.5,33,72000,0,...,1,1,1,1,0,1,0,504.5,540.5,528.5

In [108]:
offers_grouped['end_time'] = offers_grouped['received_time'] + offers_grouped['duration'] * 24
offers_grouped['viewed_on_time'] = offers_grouped.apply(lambda x: 1 if x['viewed_time'] < x['end_time'] and x['viewed_time'] != 0 else 0, axis=1)
offers_grouped['completed_on_time'] = offers_grouped.apply(lambda x: 1 if x['completed_time'] < x['end_time'] and x['completed_time'] != 0 else 0, axis=1)

# dropping misattributions (completion without view, completion before view, or view before receipt)
offers_grouped = offers_grouped.query('~(completed_time > 0 and viewed_time == 0)')
offers_grouped = offers_grouped.query('~(completed_time != 0 and completed_time < viewed_time)')
offers_grouped = offers_grouped.query('~(viewed_time != 0 and viewed_time < received_time)')

In [109]:
!pip install lifetimes #For RFM Model
!pip install -U yellowbrick #For elbow method visualisation

Collecting lifetimes
  Downloading Lifetimes-0.11.3-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: numpy>=1.10.0 in /usr/local/lib/python3.11/dist-packages (from lifetimes) (2.0.2)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from lifetimes) (1.15.3)
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.11/dist-packages (from lifetimes) (2.2.2)
Requirement already satisfied: autograd>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from lifetimes) (1.8.0)
Requirement already satisfied: dill>=0.2.6 in /usr/local/lib/python3.11/dist-packages (from lifetimes) (0.3.7)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.24.0->lifetimes) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.24.0->lifetimes) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.24.0->lifetimes) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=0.24.0->lifetimes) (1.17.0)
Downloading Lifetimes-0.11.3-py3-none-any.whl (584 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 584.2/584.2 kB 12.1 MB/s eta 0:00:00
Installing collected packages: lifetimes
Successfully installed lifetimes-0.11.3
Requirement already satisfied: yellowbrick in /usr/local/lib/python3.11/dist-packages (1.5)
Requirement already satisfied: matplotlib!=3.0.0,>=2.0.2 in /usr/local/lib/python3.11/dist-packages (from yellowbrick) (3.10.0)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from yellowbrick) (1.15.3)
Requirement already satisfied: scikit-learn>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from yellowbrick) (1.6.1)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.11/dist-packages (from yellowbrick) (2.0.2)
Requirement already satisfied: cycler>=0.10.0 in /usr/local/lib/python3.11/dist-packages (from yellowbrick) (0.12.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib!=3.0.0,>=2.0.2->yellowbrick) (1.3.2)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib!=3.0.0,>=2.0.2->yellowbrick) (4.58.4)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib!=3.0.0,>=2.0.2->yellowbrick) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib!=3.0.0,>=2.0.2->yellowbrick) (24.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib!=3.0.0,>=2.0.2->yellowbrick) (11.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib!=3.0.0,>=2.0.2->yellowbrick) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib!=3.0.0,>=2.0.2->yellowbrick) (2.9.0.post0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.0.0->yellowbrick) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.0.0->yellowbrick) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib!=3.0.0,>=2.0.2->yellowbrick) (1.17.0)

In [110]:
from yellowbrick.cluster.elbow import kelbow_visualizer

from lifetimes.utils import summary_data_from_transaction_data

In [112]:
# time to Datetime
transaction['datetime'] = transaction['time'].apply(lambda x: pd.Timestamp('2000-01-01T12') + pd.Timedelta(hours=x))
transaction.head()

rf = summary_data_from_transaction_data(transaction, 'person', 'datetime', monetary_value_col='amount')
rf.drop('T', axis=1, inplace=True)

profile.rename({'id': 'person'}, axis=1, inplace=True)
profile.set_index('person', inplace=True)

customers = profile.join(rf)
customers.head()

,age,income,income_na,gender_F,gender_M,gender_NA,gender_O,year_joined_2013,year_joined_2014,year_joined_2015,year_joined_2016,year_joined_2017,year_joined_2018,frequency,recency,monetary_value
person,,,,,,,,,,,,,,,,
0610b486422d4921ae7d2bf64640c50b,55,112000,0,1,0,0,0,0,0,0,0,1,0,2.0,21.0,27.750000
78afa995795e4d85b5d9ceeca43f5fef,75,100000,0,1,0,0,0,0,0,0,0,1,0,5.0,16.0,24.320000
e2127556f4f64592b11af22de27a7932,68,70000,0,0,1,0,0,0,0,0,0,0,1,1.0,10.0,18.420000
389bc3fa690240e798340f5a15918d5c,65,53000,0,0,1,0,0,0,0,0,0,0,1,2.0,22.0,13.445000
2eeac8d8feae4a8cad5a6af0499a211d,58,51000,0,0,1,0,0,0,0,0,0,1,0,3.0,15.0,4.433333

In [119]:
offers_grouped.rename(columns={
    'event_offer completed': 'offer_completed',
    'event_offer viewed': 'offer_viewed',
    'event_offer received': 'offer_received'
}, inplace=True)

In [117]:
offers

,person,time,offer_completed,offer_received,offer_viewed,days_passed,offer_id,age,income,income_na,...,mobile,social,web,bogo,discount,informational,event,received_time,viewed_time,completed_time
0,78afa995795e4d85b5d9ceeca43f5fef,0.5,0,1,0,0.00,9b98b8c7a33c4b65b9aebfe6a799e6d9,75,100000,0,...,1,0,1,1,0,0,offer received,0.5,0.0,0.0
2,e2127556f4f64592b11af22de27a7932,0.5,0,1,0,0.00,2906b810c7d4411798c6938adc9daaa5,68,70000,0,...,1,0,1,0,1,0,offer received,0.5,0.0,0.0
5,389bc3fa690240e798340f5a15918d5c,0.5,0,1,0,0.00,f19421c1d4aa40978ebb69ca19b0e20d,65,53000,0,...,1,1,1,1,0,0,offer received,0.5,0.0,0.0
7,2eeac8d8feae4a8cad5a6af0499a211d,0.5,0,1,0,0.00,3f207df678b143eea3cee63160fa8bed,58,51000,0,...,1,0,1,0,0,1,offer received,0.5,0.0,0.0
8,aa4862eba776480b8bb9c68455b8c2e1,0.5,0,1,0,0.00,0b1e1539f2cc45b7b9fa7c272da2e1d7,61,57000,0,...,0,0,1,0,1,0,offer received,0.5,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167574,84fb57a7fe8045a8bf6236738ee73a0f,714.5,0,0,1,29.75,5a8bc65990b245e5a138643cd4eb9837,64,113000,0,...,1,1,0,0,0,1,offer viewed,0.0,714.5,0.0
167575,abc4359eb34e4e2ca2349da2ddf771b6,714.5,0,0,1,29.75,3f207df678b143eea3cee63160fa8bed,51,68000,0,...,1,0,1,0,0,1,offer viewed,0.0,714.5,0.0
167578,8dda575c2a1d44b9ac8e8b07b93d1f8e,714.5,0,0,1,29.75,0b1e1539f2cc45b7b9fa7c272da2e1d7,60,64000,0,...,0,0,1,0,1,0,offer viewed,0.0,714.5,0.0
167579,8431c16f8e1d440880db371a68f82dd0,714.5,1,0,0,29.75,fafdcd668e3743c1bb461111dcafc2a4,39,39000,0,...,1,1,1,0,1,0,offer completed,0.0,0.0,714.5
167580,24f56b5e1849462093931b164eb803b5,714.5,1,0,0,29.75,fafdcd668e3743c1bb461111dcafc2a4,48,80000,0,...,1,1,1,0,1,0,offer completed,0.0,0.0,714.5

In [120]:
def sum_greater_than_zero(x):
    """Counts non-0 items."""
    return (x > 0).sum()

def mean_greater_than_zero(x):
    """Average non-0 items."""
    return x.replace(0, np.nan).mean()

# BOGO offers
bogo_performance = offers_grouped.query('offer_type == "bogo"').groupby(['person']).agg(
    offers_received_cnt = ('offer_received', sum_greater_than_zero),
    offers_viewed_cnt = ('offer_viewed', sum_greater_than_zero),
    offers_completed_cnt = ('offer_completed', sum_greater_than_zero),
)
bogo_performance['bogo_vr'] = bogo_performance['offers_viewed_cnt'] / bogo_performance['offers_received_cnt']
bogo_performance['bogo_cr'] = bogo_performance['offers_completed_cnt'] / bogo_performance['offers_viewed_cnt']
bogo_performance.drop(['offers_viewed_cnt', 'offers_received_cnt', 'offers_completed_cnt'], axis=1, inplace=True)

# discount offers
discount_performance = offers_grouped.query('offer_type == "discount"').groupby(['person']).agg(
    offers_received_cnt = ('offer_received', sum_greater_than_zero),
    offers_viewed_cnt = ('offer_viewed', sum_greater_than_zero),
    offers_completed_cnt = ('offer_completed', sum_greater_than_zero),
)
discount_performance['discount_vr'] = discount_performance['offers_viewed_cnt'] / discount_performance['offers_received_cnt']
discount_performance['discount_cr'] = discount_performance['offers_completed_cnt'] / discount_performance['offers_viewed_cnt']
discount_performance.drop(['offers_viewed_cnt', 'offers_received_cnt', 'offers_completed_cnt'], axis=1, inplace=True)

# informational offers view rate
informational_performance = offers_grouped.query('offer_type == "informational"').groupby(['person']).agg(
    offers_received_cnt = ('offer_received', sum_greater_than_zero),
    offers_viewed_cnt = ('offer_viewed', sum_greater_than_zero),
    offers_completed_cnt = ('offer_completed', sum_greater_than_zero),
)
informational_performance['informational_vr'] = informational_performance['offers_viewed_cnt'] / informational_performance['offers_received_cnt']
informational_performance.drop(['offers_viewed_cnt', 'offers_received_cnt', 'offers_completed_cnt'], axis=1, inplace=True)

# all offers conversion rate
total_performance = offers_grouped.query('offer_type != "informational"').groupby(['person']).agg(
    offers_received_cnt = ('offer_received', sum_greater_than_zero),
    offers_viewed_cnt = ('offer_viewed', sum_greater_than_zero),
    offers_completed_cnt = ('offer_completed', sum_greater_than_zero),
)
total_performance['total_cr'] = total_performance['offers_completed_cnt'] / total_performance['offers_viewed_cnt']
total_performance.drop(['offers_viewed_cnt', 'offers_received_cnt', 'offers_completed_cnt'], axis=1, inplace=True)

customers = customers.join(bogo_performance).join(discount_performance).join(informational_performance).join(total_performance)
customers.fillna(0, inplace=True)
customers.head()

,age,income,income_na,gender_F,gender_M,gender_NA,gender_O,year_joined_2013,year_joined_2014,year_joined_2015,...,year_joined_2018,frequency,recency,monetary_value,bogo_vr,bogo_cr,discount_vr,discount_cr,informational_vr,total_cr
person,,,,,,,,,,,,,,,,,,,,,
0610b486422d4921ae7d2bf64640c50b,55,112000,0,1,0,0,0,0,0,0,...,0,2.0,21.0,27.750000,0.0,0.0,0.0,0.0,0.0,0.000000
78afa995795e4d85b5d9ceeca43f5fef,75,100000,0,1,0,0,0,0,0,0,...,0,5.0,16.0,24.320000,1.0,1.0,0.0,0.0,1.0,1.000000
e2127556f4f64592b11af22de27a7932,68,70000,0,0,1,0,0,0,0,0,...,1,1.0,10.0,18.420000,1.0,1.0,1.0,0.5,0.0,0.666667
389bc3fa690240e798340f5a15918d5c,65,53000,0,0,1,0,0,0,0,0,...,1,2.0,22.0,13.445000,1.0,1.0,1.0,1.0,0.0,1.000000
2eeac8d8feae4a8cad5a6af0499a211d,58,51000,0,0,1,0,0,0,0,0,...,0,3.0,15.0,4.433333,0.0,0.0,1.0,0.5,0.0,0.500000

In [121]:
from google.colab import drive
drive.mount('/content/drive')

ValueError: mount failed